[package]
name        = "flo_float_encoder"
version     = "0.1.1"
authors     = ["Andrew Hunter <andrew@logicalshift.co.uk>"]
license     = "Apache-2.0"
repository  = "https://github.com/Logicalshift/flowbetween"
description = "Simple byte encoder for floating point values"

[dependencies]
