[package]
name        = "flow_between"
version     = "0.1.0"
authors     = ["Andrew Hunter"]

[dependencies]
static_service  = { path = "static_service" }

hyper           = "0.11.2"
futures         = "0.1.14"
serde           = "1.0"
serde_json      = "1.0"
