use super::state::*;
use super::storage_descriptor::*;

use flo_animation::*;

///
/// Command that can be issued to a FlowBetween instance
///
#[derive(Clone)]
pub enum FloCommand {
    /// Write out a message describing the version of FlowBetween that this is
    Version,

    /// Sets the directory to use for the catalog
    SetCatalogFolder(String),

    /// Requests the current command state
    ReadState,

    /// Sets the state for future commands
    SetState(CommandState),

    /// Sets the input animation
    ReadFrom(StorageDescriptor),

    /// Writes a new animation to the catalog with the specified name
    WriteToCatalog(String),

    /// Moves the current 'write' animation into the 'read' position
    ReadFromWriteAnimation,

    /// Lists the files in the main index
    ListAnimations,

    /// Clears the current set of edits
    ClearEdits,

    /// Reads in all of the edits from the input animation to the edit buffer
    ReadAllEdits,

    /// Writes out a summary of the edits in the edit buffer
    SummarizeEdits,

    /// Serializes the edits to the output
    SerializeEdits,

    /// Deserializes the edits from a string (as generated by SerializeEdits)
    DeserializeEdits(String),

    /// Writes all of the edits currently in the edit buffer to the output animation
    WriteAllEdits,

    /// Goes through the entire catalog and dumps it out as a set of files containing the serialized edit logs
    DumpCatalogAsEdits,

    /// Lists all the layers in the input animation (IDs and names)
    ListLayers,

    /// Selects the specified frame in the inout animation
    SelectFrame(u64, usize),

    /// Displays a list of elements for the currently selected frame
    ListElements,

    /// Writes out debugging SVG files for raycasting a particular element
    RayCastToSvg(ElementId)
}
