[package]
name        = "flo_commands"
version     = "0.2.0"
authors     = ["Andrew Hunter"]
license     = "Apache-2.0"
edition     = "2018"
repository  = "https://github.com/Logicalshift/flowbetween"
description = "Library providing scripting control of FlowBetween"
include     = [ "Cargo.toml", "LICENSE", "src/**/*", "png/**/*" ]
