[package]
name        = "flo_anim_sqlite"
version     = "0.1.0"
authors     = ["Andrew Hunter <andrew@logicalshift.co.uk>"]
license     = "Apache-2.0"

[dependencies]
flo_canvas          = { path = "../canvas" }
flo_animation       = { path = "../animation" }

rusqlite            = { version = "0.11.0", features = ["bundled"] }
desync              = { git = "https://github.com/logicalshift/desync", branch = "develop" }
