use flo_draw::canvas;
use serde::*;

///
/// Input point for a brush stroke
///
#[derive(Debug, Serialize, Deserialize, Clone, Copy, Default)]
pub struct BrushPoint {
    /// The coordinates of this point
    pub position: (f64, f64),

    /// The pressure on the stylus at this point, from 0.0 to 1.0 (or None if unsupported by the input device)
    pub pressure: Option<f64>,

    /// tilt in degrees relative to the normal to the surface of the screen along the X and Y axes (values from -90 to 90)
    pub tilt: Option<(f64, f64)>,

    /// If the device supports detecting rotation around its own axis, this is amount of rotation in degrees (values from -180 to 180)
    pub rotation: Option<f64>,

    /// If the device has a 'flow rate' adjustment (emulating an airbrush, for example) this is the value of that (from 0.0 to 1.0).
    pub flow_rate: Option<f64>,

    /// The radius of the 'daub' that should be generated by this brush point (centered on the position)
    pub daub_radius: Option<f64>,

    /// The transform that should be applied to the daub shape (after scaling to the radius but before transforming to the position value)
    pub daub_transform: Option<canvas::Transform2D>,
}

impl BrushPoint {
    ///
    /// Computes the distance from this point to another point
    ///
    #[inline]
    pub fn distance_to(&self, other: &BrushPoint) -> f64 {
        let dx = self.position.0 - other.position.0;
        let dy = self.position.1 - other.position.1;

        (dx*dx + dy*dy).sqrt()
    }
}
