// FlowBetween, a tool for creating vector animations
// Copyright (C) 2026 Andrew Hunter
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

use super::brush_point::*;
use crate::scenery::document::canvas::*;

use flo_scene::*;
use serde::*;

use futures::prelude::*;
use futures::stream::{BoxStream};

use std::sync::*;

///
/// Brushes respond to requests by returning functions that pipe results of one type to another. The brush
/// tool assembles these responses into a pipeline that generates the output shape from the input set of points
///
pub enum BrushResponse {
    /// Filters the input points for the brush stroke (eg, for applying smoothing to the brush stroke, but also for things like
    /// setting the brush radius)
    Points(Arc<dyn Send + Sync + Fn(BoxStream<'static, BrushPoint>) -> BoxStream<'static, BrushPoint>>),

    /// Generates the base shapes that are added to the canvas
    ///
    /// In general, there should only be one of these for a brush. Using more than one will generate multiple
    /// shapes in the canvas.
    ///
    /// The shape generator should accumulate the points (ie, generate shapes by using all the points received so far
    /// plus the new set). Ie, we stream in the points we get from the input and stream out the intermediate shapes that
    /// are shown as the user draws with the brush. This means that the brush can create previews quickly by reusing the
    /// data that it has generated already. (If we're regenerating from a brush stroke, this will receive only a single
    /// set of brush points: we only stream a large set if we're showing an interactive preview to the user)
    ShapeGenerator(Arc<dyn Send + Sync + Fn(BoxStream<'static, Vec<BrushPoint>>) -> BoxStream<'static, ShapeWithProperties>>),

    /// Modifies the shapes: often to apply properties like colour to them
    ///
    /// This is how things like the colour or the line width tool applies its properties to the final brush stroke
    Shapes(Arc<dyn Send + Sync + Fn(BoxStream<'static, Vec<ShapeWithProperties>>) -> BoxStream<'static, Vec<ShapeWithProperties>>>),
}

impl SceneMessage for BrushResponse {
    fn serializable() -> bool { false }
}

impl Serialize for BrushResponse {
    fn serialize<S>(&self, _serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        use serde::ser::*;
        Err(S::Error::custom("PhysicsLayer cannot be serialized"))
    }
}

impl<'de> Deserialize<'de> for BrushResponse {
    fn deserialize<D>(_deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        use serde::de::*;
        Err(D::Error::custom("PhysicsLayer cannot be serialized"))
    }
}

///
/// Pipes together a brush description, building up a stream of shapes representing the output shapes
///
pub fn create_shape_stream<'a>(points: impl 'static + Send + Stream<Item=BrushPoint>, responses: impl Iterator<Item=&'a BrushResponse>) -> impl 'static + Send + Stream<Item=Vec<ShapeWithProperties>> {
    // Box up the initial points stream
    let points = points.boxed();

    // Build up functions to create the final stream using the responses in the order that they're supplied
    let mut points_stream:      Box<dyn Fn(BoxStream<'static, BrushPoint>)               -> BoxStream<'static, BrushPoint>>               = Box::new(|stream| stream);
    let mut generator_stream:   Box<dyn Fn(BoxStream<'static, Vec<BrushPoint>>)          -> BoxStream<'static, Vec<ShapeWithProperties>>> = Box::new(|stream| stream.map(|_| vec![]).boxed());
    let mut shape_stream:       Box<dyn Fn(BoxStream<'static, Vec<ShapeWithProperties>>) -> BoxStream<'static, Vec<ShapeWithProperties>>> = Box::new(|stream| stream);

    for response in responses {
        // TODO: the shape generator should combine the shapes generated by the other generators to create a vec of all the generated shapes
        match response {
            BrushResponse::Points(point_fn)             => { points_stream      = Box::new(move |stream| (points_stream)(point_fn(stream))); },
            BrushResponse::Shapes(shape_fn)             => { shape_stream       = Box::new(move |stream| (shape_stream)(shape_fn(stream))); },
            BrushResponse::ShapeGenerator(generator_fn) => { generator_stream   = Box::new(move |stream| generator_fn(stream).map(|shape| vec![shape]).boxed()); },
        }
    }

    // Create the final stream
    let points_chunks       = (points_stream)(points).ready_chunks(10_000);
    let generated_shapes    = (generator_stream)(points_chunks.boxed());
    let modified_shapes     = (shape_stream)(generated_shapes);

    modified_shapes
}
