use super::brush_point::*;
use crate::scenery::document::canvas::*;

use flo_curves::bezier::path::*;
use flo_curves::bezier::vectorize::*;

use futures::prelude::*;

use std::sync::*;

///
/// Brush stream that builds up a shape by drawing the supplied 'daub' shape
///
/// This returns new shapes for every batch of brush points that it receives (typically generated by `ready_chunks()` from a stream of points from
/// the UI). To generate a single shape, just send a single batch of points.
///
pub fn daub_brush_stream<'a>(daub: &'a (impl Send + Sync + ColumnSampledContour), points: impl 'a + Send + Stream<Item=Vec<BrushPoint>>) -> impl 'a + Send + Stream<Item=ShapeWithProperties> {
    // Used for scaling the daub contour
    let default_size = daub.contour_size();
    let default_size = (default_size.0 as f64, default_size.1 as f64);
    let radius_ratio = 2.0 / (default_size.0.max(default_size.1));

    // Start with an empty range contour
    let brush_contour = ColumnRangeContour::default();

    // Prepare the points for reading
    let points = Box::pin(points);

    // Stream the points and generate the shapes that result from each set
    stream::unfold((brush_contour, daub, points), move |(mut brush_contour, daub, mut points)| async move {
        // Fetch the next batch of points
        let Some(next_points) = points.next().await else { return None };

        // Add to our contour to build the brush stroke
        for point in next_points {
            // Scale the daub
            let radius  = point.daub_radius.unwrap_or(1.0);
            let scale   = radius_ratio * radius;
            let daub    = ScaledContour::from_contour(daub, scale, (0.0, 0.0));

            // Center around the x, y position
            let x = point.position.0 - default_size.0*scale*0.5;
            let y = point.position.1 - default_size.1*scale*0.5;

            // Add to the brush contour
            brush_contour.add_contour(&daub, (x, y));
        }

        // Generate a shape for the current set of daubs
        let path    = trace_paths_from_intercepts::<WorkingSubpath>(&brush_contour, 0.1);
        let shape   = CanvasShape::Path(WorkingSubpath::to_canvas_path(&path));
        let shape   = ShapeWithProperties {
            shape:      shape,
            shape_type: ShapeType::default(),
            shape_time: FrameTime::from_nanos(0),
            properties: Arc::new(vec![]),
            group:      vec![],
        };

        Some((shape, (brush_contour, daub, points)))
    })
}
