use super::brush_point::*;
use crate::scenery::document::canvas::*;

use flo_curves::*;
use flo_curves::bezier::*;
use flo_curves::bezier::path::*;
use flo_curves::bezier::vectorize::*;

use futures::prelude::*;

use std::sync::*;

///
/// Brush stream that builds up a shape by drawing the supplied 'daub' shape
///
/// This returns new shapes for every batch of brush points that it receives (typically generated by `ready_chunks()` from a stream of points from
/// the UI). To generate a single shape, just send a single batch of points.
///
pub fn daub_brush_stream<'a>(daub: Arc<impl 'a + Send + Sync + ColumnSampledContour>, points: impl 'a + Send + Stream<Item=Vec<BrushPoint>>, max_error: f64) -> impl 'a + Send + Stream<Item=ShapeWithProperties> {
    // Used for scaling the daub contour
    let default_size = daub.contour_size();
    let default_size = (default_size.0 as f64, default_size.1 as f64);
    let radius_ratio = 2.0 / (default_size.0.max(default_size.1));

    // Start with an empty range contour
    let brush_contour = ColumnRangeContour::default();

    // Prepare the points for reading
    let points = Box::pin(points);

    // Stream the points and generate the shapes that result from each set
    stream::unfold((brush_contour, daub, points), move |(mut brush_contour, daub, mut points)| async move {
        // Fetch the next batch of points
        let Some(next_points) = points.next().await else { return None };

        // Add to our contour to build the brush stroke
        for point in next_points {
            // Scale the daub
            let radius  = point.daub_radius.unwrap_or(1.0);
            let scale   = radius_ratio * radius;
            let daub    = ScaledContour::from_contour(&*daub, scale, (0.0, 0.0));

            // Center around the x, y position
            let x = point.position.0 - default_size.0*scale*0.5;
            let y = point.position.1 - default_size.1*scale*0.5;

            // Add to the brush contour
            brush_contour.add_contour(&daub, (x, y));
        }

        // Generate a shape for the current set of daubs
        let path    = trace_paths_from_intercepts::<WorkingSubpath>(&brush_contour, max_error);
        let shape   = CanvasShape::Path(WorkingSubpath::to_canvas_path(&path));
        let shape   = ShapeWithProperties {
            shape:      shape,
            shape_type: ShapeType::default(),
            shape_time: FrameTime::from_nanos(0),
            properties: Arc::new(vec![]),
            group:      vec![],
        };

        Some((shape, (brush_contour, daub, points)))
    })
}

///
/// Creates a brush stream that generates shapes by fitting the curve and applying an offset according to the radius stored in the points
///
/// This generates a shape for every set of points that is passed in. The input is the set of points being generated by the UI
/// as the user moves their tool across the canvas, so the shapes generated are made by combining all the points received to
/// this point (so each shape is the partial path generated at a point in time).
///
/// To generate a single shape, just pass in a single batch of points.
///
pub fn width_brush_stream<'a>(points: impl 'a + Send + Stream<Item=Vec<BrushPoint>>, max_error: f64) -> impl 'a + Send + Stream<Item=ShapeWithProperties> {
    use std::iter;

    let all_points = vec![];

    stream::unfold((all_points, Box::pin(points)), move |(mut all_points, mut input_points)| async move {
        loop {
            // Read the next set of points
            let Some(new_points) = input_points.next().await else { return None };

            // Add the new points to the 'all points' list (map to Coord3)
            all_points.extend(new_points.iter().map(|brush_point| Coord3(brush_point.position.0, brush_point.position.1, brush_point.daub_radius.unwrap_or(1.0))));

            // Fit the points to a curve (skip producing a shape if we can't fit)
            let Some(wide_curve) = Curve::<Coord3>::fit_from_points(&all_points, max_error) else { continue; };

            let narrow_curve = wide_curve.iter().map(|curve| {
                let (sp, (cp1, cp2), ep) = curve.all_points();
                let (sp, (cp1, cp2), ep) = (WorkingPoint { x:sp.0, y:sp.1 }, (WorkingPoint { x:cp1.0, y:cp1.1 }, WorkingPoint { x:cp2.0, y:cp2.1 }), WorkingPoint { x:ep.0, y:ep.1 });

                Curve::from_points(sp, (cp1, cp2), ep)
            }).collect::<Vec<_>>();

            // Offset narrow_curve to generate the points 'above' and 'below' the main curve
            let offset_up = narrow_curve.iter().zip(wide_curve.iter())
                .flat_map(|(narrow, wide)| offset_lms_sampling(narrow, |t| wide.point_at_pos(t).2, |_| 0.0, 20, max_error).unwrap_or_else(|| vec![]))
                .collect::<Vec<_>>();

            let offset_down = narrow_curve.iter().zip(wide_curve.iter())
                .flat_map(|(narrow, wide)| offset_lms_sampling(narrow, |t| -wide.point_at_pos(t).2, |_| 0.0, 20, max_error).unwrap_or_else(|| vec![]))
                .rev()
                .collect::<Vec<_>>();

            // Create the shape
            let subpath = WorkingSubpath {
                start_point: offset_up[0].start_point,
                actions:     offset_up.iter()
                                .map(|curve| { let (cp1, cp2) = curve.control_points(); WorkingPathAction::CubicCurve { end: curve.end_point(), cp1, cp2 } })
                                .chain(iter::once(WorkingPathAction::Line(offset_down[0].start_point())))
                                .chain(offset_down.iter().map(|curve| { let (cp1, cp2) = curve.control_points(); WorkingPathAction::CubicCurve { end: curve.end_point(), cp1, cp2 } }))
                                .chain(iter::once(WorkingPathAction::Close))
                                .collect()
            };

            let shape = WorkingSubpath::to_canvas_path(&[subpath]);
            let shape = CanvasShape::Path(shape);
            let shape = ShapeWithProperties {
                shape:      shape,
                shape_type: ShapeType::default(),
                shape_time: FrameTime::from_nanos(0),
                properties: Arc::new(vec![]),
                group:      vec![],
            };

            return Some((shape, (all_points, input_points)));
        }
    })
}
