[package]
name        = "flo_gtk_ui"
version     = "0.2.0"
authors     = ["Andrew Hunter"]
edition     = "2018"
license     = "Apache-2.0"
repository  = "https://github.com/Logicalshift/flowbetween"
description = "Gtk+ implementation pipe for flo_ui"
include     = [ "Cargo.toml", "src/**/*", "style/**/*" ]

[dependencies]
flo_ui              = "0.2"
flo_canvas          = "0.4"
flo_stream          = "0.7"
flo_render          = { version = "0.4", features = [ "opengl" ] }
flo_render_canvas   = "0.4"
desync              = "0.7"

gtk                 = { version = "0.9", features = ["v3_20"] }
gdk                 = { version = "0.13", features = ["v3_18"] }
gdk-sys             = { version = "0.10", features = ["v3_18"] }
gdk-pixbuf          = "0.9"
gio                 = { version = "0.9", features = ["v2_44"] }
glib                = "0.10"
cairo-rs            = "0.9"
gl                  = "0.14"
epoxy               = "0.1"
shared_library      = "0.1"
futures             = "0.3"
anymap              = "0.12"
itertools           = "0.9"
time                = "0.2"
lazy_static         = "1.2"
