[package]
name        = "flo_http_ui_actix"
version     = "0.1.1"
authors     = ["Andrew Hunter"]
license     = "Apache-2.0"
repository  = "https://github.com/Logicalshift/flowbetween"
description = "HTTP+HTML implementation pipe for flo_ui built on the Actix web framework"

include     = [ "Cargo.toml", "src/**/*", "js/**/*" ]

[dependencies]
flo_ui              = { path = "../../ui", version = "0.1" }
flo_binding         = { path = "../../binding", version = "0.1" }
flo_canvas          = { path = "../../canvas", version = "0.1" }
flo_http_ui         = { path = "../http_ui", version = "0.1" }
flo_static_files    = { path = "../../static_files", version= "0.1" }
flo_logging         = { path = "../../logging", version = "0.1" }

actix               = "0.7"
actix-web           = "0.7"
bytes               = "0.4"
futures             = "0.1"
serde_json          = "1.0"
lazy_static         = "1.2"
percent-encoding    = "1.0"
