[package]
name                = "flo_cocoa"
version             = "0.2.0"
edition             = "2018"
authors             = ["Andrew Hunter"]
license             = "Apache-2.0"
repository          = "https://github.com/Logicalshift/flowbetween"
description         = "Interoperability between the FlowBetween XCode and Rust projects"

[lib]
name                = "flo_cocoa"
crate-type          = ["staticlib", "cdylib"]

[dependencies]
flo_animation       = "0.2"
flo_sqlite_storage  = "0.1"
flo_binding         = "2.0"
flo_ui_files        = "0.2"
flo_ui              = "0.2"
flo_canvas          = "0.4"
flo_logging         = "0.2"
flo                 = "0.2"
flo_cocoa_pipe      = "0.2"
flo_cocoa_ui        = "0.2"

objc                = "0.2"
futures             = "0.3"
serde               = "1.0"
serde_derive        = "1.0"
serde_json          = "1.0"
log                 = "0.4"
env_logger          = "0.7"
pretty_env_logger   = "0.4"
