[package]
name            = "flo_cocoa"
version         = "0.1.0"
edition         = "2018"
authors         = ["Andrew Hunter"]
license         = "Apache-2.0"
repository      = "https://github.com/Logicalshift/flowbetween"
description     = "Interoperability between the FlowBetween XCode and Rust projects"

[dependencies]
flo             = { path = "../../flo",     version = "0.1" }
flo_cocoa_pipe  = { path = "../cocoa_pipe", version = "0.1" }
flo_cocoa_ui    = { path = "../cocoa_ui",   version = "0.1" }

objc            = "0.2"
