[package]
name                = "flo_cocoa"
version             = "0.2.0"
edition             = "2018"
authors             = ["Andrew Hunter"]
license             = "Apache-2.0"
repository          = "https://github.com/Logicalshift/flowbetween"
description         = "Interoperability between the FlowBetween XCode and Rust projects"

[lib]
name                = "flo_cocoa"
crate-type          = ["staticlib", "cdylib"]

[dependencies]
flo_animation       = { path = "../../animation",       version="0.2" }
flo_sqlite_storage  = { path = "../../sqlite_storage",  version="0.1" }
flo_binding         = { git = "https://github.com/Logicalshift/flo_binding", version = "2.0" }
flo_ui_files        = { path = "../../ui_files",        version="0.2" }
flo_ui              = { path = "../../ui",              version="0.2" }
flo_canvas          = { path = "../../canvas",          version="0.2" }
flo_logging         = { path = "../../logging",         version="0.2" }
flo                 = { path = "../../flo",             version="0.2" }
flo_cocoa_pipe      = { path = "../cocoa_pipe",         version="0.2" }
flo_cocoa_ui        = { path = "../cocoa_ui",           version="0.2" }

objc                = "0.2"
futures             = "0.3"
serde               = "1.0"
serde_derive        = "1.0"
serde_json          = "1.0"
log                 = "0.4"
env_logger          = "0.7"
pretty_env_logger   = "0.4"
