[workspace]
members = [
    "motion_effect",
    "shatter",
    "shatter_transform"
]

[patch.crates-io]
flo_canvas_animation    = { path = ".." }
flo_curves              = { git = "https://github.com/Logicalshift/flo_curves" }
