[package]
name        = "flo"
version     = "0.1.0"
authors     = ["Andrew Hunter"]
license     = "Apache-2.0"
repository  = "https://github.com/Logicalshift/flowbetween"
description = "User interface description for FlowBetween"

include     = [ "Cargo.toml", "src/**/*", "svg/**/*" ]

[dependencies]
flo_animation   = { path = "../animation", version = "^0.1.0" }
flo_curves      = { path = "../curves", version = "^0.1.0" }
flo_binding     = { path = "../binding", version = "^0.1.0" }
flo_ui          = { path = "../ui", version = "^0.1.0" }
flo_canvas      = { path = "../canvas", version = "^0.1.0" }
desync          = "^0.1.2"

serde           = "^1.0.0"
serde_derive    = "^1.0.0"
serde_json      = "^1.0.0"
lazy_static     = "^1.0.0"
futures         = "^0.1.17"
itertools       = "0.7"
