[package]
name        = "flo"
version     = "0.1.0"
authors     = ["Andrew Hunter"]

[dependencies]
animation       = { path = "../animation" }
curves          = { path = "../curves" }
binding         = { path = "../binding" }
ui              = { path = "../ui" }
canvas          = { path = "../canvas" }
desync          = { git = "https://github.com/logicalshift/desync", branch = "develop" }

serde           = "^1.0.0"
serde_derive    = "^1.0.0"
serde_json      = "^1.0.0"
lazy_static     = "^1.0.0"
futures         = "^0.1.17"
