[package]
name        = "flo"
version     = "0.1.1"
authors     = ["Andrew Hunter"]
license     = "Apache-2.0"
repository  = "https://github.com/Logicalshift/flowbetween"
description = "User interface description for FlowBetween"

include     = [ "Cargo.toml", "src/**/*", "svg/**/*" ]

[dependencies]
flo_animation   = { path = "../animation", version = "^0.1.0" }
flo_anim_sqlite = { path = "../anim_sqlite", version = "0.2" }
flo_curves      = { git = "https://github.com/Logicalshift/flo_curves", version = "^0.2.2" }
flo_stream      = { git = "https://github.com/Logicalshift/flo_stream", version = "0.3" }
flo_binding     = { git = "https://github.com/Logicalshift/flo_binding", version = "1.0" }
flo_ui          = { path = "../ui", version = "^0.1.0" }
flo_canvas      = { path = "../canvas", version = "^0.1.0" }
flo_ui_files    = { path = "../ui_files", version = "^0.1.0" }
desync          = "0.4"

serde           = "^1.0.0"
serde_derive    = "^1.0.0"
serde_json      = "^1.0.0"
lazy_static     = "^1.0.0"
futures         = "^0.1.17"
itertools       = "0.8"
