[package]
name        = "flo"
version     = "0.1.0"
authors     = ["Andrew Hunter"]
license     = "Apache-2.0"

[dependencies]
flo_animation   = { path = "../animation" }
flo_curves      = { path = "../curves" }
flo_binding     = { path = "../binding" }
flo_ui          = { path = "../ui" }
flo_canvas      = { path = "../canvas" }
desync          = { git = "https://github.com/logicalshift/desync", branch = "develop" }

serde           = "^1.0.0"
serde_derive    = "^1.0.0"
serde_json      = "^1.0.0"
lazy_static     = "^1.0.0"
futures         = "^0.1.17"
