[package]
name        = "flo"
version     = "0.2.0"
authors     = ["Andrew Hunter"]
license     = "Apache-2.0"
edition     = "2018"
repository  = "https://github.com/Logicalshift/flowbetween"
description = "User interface description for FlowBetween"

include     = [ "Cargo.toml", "src/**/*", "svg/**/*" ]

[dependencies]
flo_animation       = { path = "../animation", version = "0.2" }
flo_curves          = { git = "https://github.com/Logicalshift/flo_curves", version = "0.4" }
flo_stream          = { git = "https://github.com/Logicalshift/flo_stream", version = "0.5" }
flo_binding         = { git = "https://github.com/Logicalshift/flo_binding", version = "2.0" }
flo_ui              = { path = "../ui", version = "0.2" }
flo_canvas          = { path = "../canvas", version = "0.2" }
flo_ui_files        = { path = "../ui_files", version = "0.2" }
desync              = { git = "https://github.com/Logicalshift/desync", branch = "v0.7.0", version = "0.7" }

serde               = "1.0"
serde_derive        = "1.0"
serde_json          = "1.0"
lazy_static         = "1.2"
futures             = "0.3"
itertools           = "0.9"
