use super::traits::*;

use flo_curves::*;
use flo_canvas::*;

use std::time::Duration;

///
/// Computes or retrieves the onion skin for a particular layer at a specified time
///
pub fn onion_skin_for_layer<LayerType: Layer>(layer: &LayerType, when: Duration) -> Vec<Draw> {
    if let Some(onion_skin) = layer.get_canvas_cache_at_time(when).retrieve(CacheType::OnionSkinLayer) {
        // If the layer has a cached version of the onion skin, then just use that
        onion_skin
    } else {
        // The onion skin is the path generated by adding up all of the paths contained in the layer at this time
        unimplemented!()
    }
}
