[package]
name        = "animation"
version     = "0.1.0"
authors     = ["Andrew Hunter"]

[dependencies]
ui                  = { path = "../ui" }
curves              = { path = "../curves" }

typemap             = "^0.3.3"
modifier            = "^0.1.0"
serde               = "^1.0.0"
serde_derive        = "^1.0.0"
