[package]
name        = "flo_http_ui"
version     = "0.2.0"
authors     = ["Andrew Hunter"]
license     = "Apache-2.0"
edition     = "2018"
repository  = "https://github.com/Logicalshift/flowbetween"
description = "HTTP+HTML implementation pipe for flo_ui"

include     = [ "Cargo.toml", "src/**/*", "js/**/*" ]

[dependencies]
flo_ui              = { path = "../../ui", version = "0.2" }
flo_binding         = { git = "https://github.com/Logicalshift/flo_binding", version = "2.0" }
flo_canvas          = { path = "../../canvas", version = "0.2" }
flo_stream          = { git = "https://github.com/Logicalshift/flo_stream", version = "0.5" }
flo_logging         = { path = "../../logging", version = "0.2" }

serde               = "1.0"
serde_json          = "1.0"
serde_derive        = "1.0"
svg                 = "0.8"
uuid                = { version = "0.8", features = [ "v4" ] }
percent-encoding    = "2.1"
futures             = { version = "0.3", features = [ "thread-pool" ] }
desync              = { git = "https://github.com/Logicalshift/desync", branch = "v0.7.0", version = "0.7" }
itertools           = "0.9"
bytes               = "0.5"
lazy_static         = "1.2"