[package]
name        = "flo_gtk_ui"
version     = "0.1.0"
authors     = ["Andrew Hunter"]
license     = "Apache-2.0"
repository  = "https://github.com/Logicalshift/flowbetween"
description = "Gtk+ implementation pipe for flo_ui"

[dependencies]
flo_ui          = { path = "../ui", version = "^0.1.0" }
flo_canvas      = { path = "../canvas", version = "^0.1.0" }

gtk             = "0.4.0"
glib            = "0.5.0"
futures         = "^0.1.17"
anymap          = "^0.12.1"
lazy_static     = "^1.0.0"
