use super::undo_layer_edits::*;

use crate::traits::*;
use crate::editor::*;
use crate::storage::*;

use flo_stream::*;

use futures::prelude::*;
use futures::future::{select, Either};
use futures::executor;
use futures_timer::{Delay};

use std::mem;
use std::sync::*;
use std::time::{Duration};

//
/// Deserializes some edits and runs them on the animation. The edit string can be generated
/// by the diagnostics command line tool.
///
pub fn deserialize_edits(edits: &str) -> Vec<AnimationEdit> {
    let mut source              = edits.chars();
    let mut deserialized_edits  = vec![];

    loop {
        match source.next() {
            None        => { break; },
            Some('\n')  |
            Some(' ')   |
            Some('\t')  |
            Some('\r')  => { /* Newlines and whitespace are ignored */ },

            Some(';')   => {
                // Comment ended by a newline
                loop {
                    match source.next() {
                        Some('\n')  |
                        Some('\r')  | 
                        None        => { break; },
                        _other      => { }
                    }
                }
            }

            Some(other) => {
                // Serialized edit, ended by a newline
                let mut edit = String::new();
                edit.push(other);

                // Read until the newline to get the serialized edit
                loop {
                    match source.next() {
                        Some('\n')  => { break; }
                        None        => { break; },
                        Some(other) => { edit.push(other); }
                    }
                }

                // Attempt to deserialize the edit
                let animation_edit = AnimationEdit::deserialize(&mut edit.chars()).unwrap();

                // Add to the edit buffer
                deserialized_edits.push(animation_edit);
            }
        }
    }

    deserialized_edits
}

///
/// Deserializes a set of edits in FlowBetween's serialized format and tests that the last action can be undone successfully
///
pub async fn test_undo_last_action_serialized(edits: &str) {
    // Deserialize the edit
    let edits = deserialize_edits(edits);

    test_undo_last_action(edits).await;
}

///
/// Given a set of animation edits, finds the last action and tests if undoing it leaves the animation in the same state
///
pub async fn test_undo_last_action(edits: Vec<AnimationEdit>) {
    let mut edits = edits;

    // Remove the final 'FinishAction' if there is one
    if edits.last() == Some(&AnimationEdit::Undo(UndoEdit::FinishAction)) {
        edits.pop();
    }

    // Search for the last 'FinishAction' index
    let last_finish_action_idx = edits.iter()
        .enumerate()
        .filter(|(_idx, edit)| *edit == &AnimationEdit::Undo(UndoEdit::FinishAction))
        .map(|(idx, _edit)| idx)
        .last()
        .unwrap();

    // Split into the 'setup' actions and the action we're going to undo
    let undo_edits  = edits.split_off(last_finish_action_idx+1);
    let setup_edits = edits;

    // Create the animation
    let in_memory_store = InMemoryStorage::new();
    let animation       = create_animation_editor(move |commands| in_memory_store.get_responses(commands).boxed());

    // Perform the setup edits
    animation.edit().publish(Arc::new(setup_edits)).await;
    animation.edit().when_empty().await;

    // Read the layers
    let all_layers_before = read_all_layers(&animation).await;

    // Perform the undo action and capture the retired edit
    // The undo action appears when the edits are retired: start reading them from this point
    let timeout             = Delay::new(Duration::from_secs(10));
    let mut retired_edits   = animation.retired_edits();

    // Publish the undo test edits
    let undo_edits          = Arc::new(undo_edits);
    animation.edit().publish(Arc::clone(&undo_edits)).await;
    animation.edit().when_empty().await;

    // The next set of edits from the retired_edits stream should be the undo edits
    let retired_edit    = match select(retired_edits.next(), timeout).await {
        Either::Right(_)    => { assert!(false, "Timed out"); unimplemented!() }
        Either::Left(edits) => edits.0.unwrap()
    };

    println!("Committed: {}", retired_edit.committed_edits().iter().fold(String::new(), |string, elem| format!("{}\n    {:?}", string, elem)));
    println!();
    println!("Reverse: {}", retired_edit.reverse_edits().iter().fold(String::new(), |string, elem| format!("{}\n    {:?}", string, elem)));

    mem::drop(retired_edits);

    // Read the layers during the edit and make sure that there's something to undo
    let during_edit     = read_all_layers(&animation).await;
    assert!(all_layers_before != during_edit);

    // Undo the edit and make sure it restores the original state
    let reverse_edits       = retired_edit.reverse_edits();
    animation.edit().publish(reverse_edits).await;
    animation.edit().when_empty().await;

    let all_layers_after = read_all_layers(&animation).await;

    assert!(all_layers_after == all_layers_before);
}

#[test]
fn fill_circle() {
    executor::block_on(async { 
        test_undo_last_action_serialized("
            SAAAAAAAAeCEAAAAAAA4QCE
            +A
            LANHMFWelJHIxA
            LA+tAAAAAA
            LAPtAAAAAA*+AIAAAAg+AAAAoABAAAICB+
            LAPtAAAAAAP+BAAAAoABAAAg/AHAAAAAAAAAyCBAAAAAAAAAg/A
            U-
            U-
            LAPtAAAAAA*+DIAAAAg+AAAAoABAAAICB+
            LAPtAAAAAAP+EAAAAoABAAAg/AHAAAAAAAAAyCBAAAAAAAAAg/A
            LAPtAAAAAAS+CAwFAAo0L1ERAAYufkGRS9PAABAcBj9PAAA4AAA8PA8Pk+PAAABAAAAAAAAK+PAAACAAAAAAAAj9PAAA9/PAAAAAAI9PAAACAAAAAAAAh8Pm/PBAAAAAAAAU8PM/PAAAAAAAAAF7PZ/PAAAAAAAAA46PM/PAAAAAAAAAp5PM/PAAAAAAAAAHXPa2PAAAAAAAAA+2P+9PAAAAAAAAAy3Px9PCAAAAAAAAy3P+9PAAAAAAAAAa4PL+PAAAA8PAAAimP66PAAAAAAAAAs7P/+PDAAAAAA8Ph8Pm/PBAAAAAAAAI9PAAAAAAAAAAAAK+PAAABAAAAAAAAk+PAAABAAAAAAAA/+PAAA+/PAAAAAAAAAAAA+/PAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+/PAAAAAAAAAAAAAAAA8PAAAAAAaAA9/PAAAAAAcBABBA//PAAAAAAoIAoBA//PAAAAAAfDAAAA8/PAAAAAASDAAAA+/PAAAAAAgaAOBA9/PAAAAAASDABBAx/PAAAAAA4CAOBA//PAAAAAAdCA0AAAAAAAAAAA2BABBAAAAAAAAAAcBA0AACAAAAAAAABBAaAACAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAA8PAAAAAAAAACAAAAAAAAj9PAAABAAAAAAAAu8PAAABAAAAAAAAs7Py+PAAAAAAAAAr6Pl+PAAAAAAAAAr6PY+PAAAAAAAAA25Px9PAAAAAAAAAP5PY+PAAAAAAAAAa4Px9PCAAAAAAAAKgPB3PCAAAAAAAAa4PW9PEAAAAAAEA04P88PAAAAAAAAA2qPm1PAAAAAAAAAX+PAAA//PAAAAAAM/PM/PAAAAAAAAAAAAm/P+/PAAAAAAAAAAAABAAAAAAEAAAAAAA//PAAAAAAaAAAAA//PAEAAAA4CAAAAAAAAAAAAA4CAAAA//PAAAAAAzHAoBA//PAAAAAAUEAPCA//PAAAAAAUEAoBA//PAAAAAAuEAPCAAAAAAAAAAUEAPCAAAAAAAA8PzHASEAAAAAAAAEASDAoBAAAAAAAAEA4CA0AAAAAAAAAEAdCAbBABAAAAAAAA2BA0AACAAAAAAEAcBAaAAJAAAAAAAAnAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAA//PAAAAAAAAAAAAAAAAAAAAAp5PAAACAAAAAAAAI9Pm/PAAAAAAA8Ps7PM/PBAAAAAAAAr6PL+PBAAAAAAEA46P+9P//PAAAAAAr6Px9PAAAAAAAEAEzPe5PAAAAAAAEAO5PI8PAAAAAAAAA4rPJzPAAAAAAAAAD6PI8P//PAAAAAA46PI8PAAAAAAAAAs7P88PBAAAAAAAAh8PW9PBAAAAAAAAI9PY+P+/PAAAAAAk+PZ/P+/PAAAAAA/+Pm/PAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAnAAAAA+/PAAAAIAdCAaAA//PAAAA8PsDA1BA//PAAAAIAgLAIGAAAAAAAA8P5DAcCA+/PAAAA8P5DAPCAAAAAAAA8PCJA8GAAAAAAAAAAdCACCAFAAAAAA8PBBA1BACAAAAAAAAaAAoBACAAAAAAAAAAABBACAAAEAAAAAAA0AACAAAAAAIAAAAaAA//PAAAA8PAAAAAAAAAAAAAAAk+PAAABAAAAAAAAP5PAAAAAAAAAA8PU8PAAAAAAAAAA8Px2Pu7PCAAAAAAAAQ6Pi8P//PAAAA8PPjP8pP//PAAAAAAL3Pq4PAAAAAAAAAk2Po3PAAAAAAA8PW2PB3PAAAAAAAAA81PA2PAAAAAAAAAYZPiWPAAAAAAAAAa4PA2P//PAAAAAAP5PB3PAAAAAAAAAQ6Po3P9/PAAAAAAs7Pq4P+/PAAAAAAu8Pf6P7/PAAAAAA99Pq4P9/PAAAAAAAAAL+P//PAEAAAAAAAAAA9/PAAAAAAAAAAAA6/PAAAAAAnAAAAA4/PAAAA8PsDAAAA2/PAAAAAA5DAeDA2/PAAAAAAUEA4DAz/PAAAAAAVFAUFAw/PAAAAAAVFAGFAx/PAAAAAA5KADMA2/PAAAAAAVFAIGA5/PAAAAAAVFAIGADAAAAAAAAUEAhFAKAAAAAAAAUEAuFAQAAAAAAAA5DAGFASAAAAAAAAQCASEARAAAAAAAADCAFEAOAAAAAAAABBA3CAKAAAAAAAAAAAPCAGAAAAAAAAAAAoBADAAAAAAAAAAAnAABAAAAAAAAAAAAAABAAAAAAAAAAAAAABAAAAAAAAv1PX9PBAAAAAAAAU8Pi8PEAAAEAAAAF7Pu7PCAAAAAAAAS7Ps6PCAAAAAAAAGlP1aPBAAAAAAAAQ6Pa2PCAAAAAAAAp5Pz1PAAAAAAAAA25PL1PAAAAAAAAAp5PL1PAAAAAAAAAg0PsnPAAAAAAAAAQ6P8yP+/PAAAAAAr6P9zP+/PAAAAAA+2PUoP+/PAEAAAAH8PL1P9/PAAAAAAI9Pa2P8/PAAAAAAI9Pq4P7/PAAAAAAk+Pe5P4/PAAAAAA/+PE5Pp/PAAAAAAAAAM/P1/PAAAAAAAAAAAAp/PAAAAAAAAAAAAa/PAAAAAAnAAAAAu/PAAAAAA
            U-
            LAPtAAAAAAS+FAaAAo21XDRAAYzyyFRv9PAIBAcB25PAAAGAAAAAAAAj9PAAAHAAAAAAAAK+Pk9PBAAAAAAAAj9PX9PCAAAAAAAAI9Pi8PDAAAAAAAAI9Pu7PAAAAAAAAAH8PS6PCAAAAAAAAu8PF6PBAAAAAAAAHtPGePBAAAAAAAA46PL1PEAAAAAAAAp5Px0PAAAAAAAAA46PjzPAAAAAAAAAD6PhyPAAAAAAAAA46PHyPAAAAAAAAAQ6PHyPBAAAAAAAAs7P5wP//PAAAAAAy3PajP9/PAAAA8Pj9PvyP5/PAEAAAAK+PX0P7/PAAAAAAk+Pm1P5/PAAAAAAZ/P02P2/PAAAAAAAAAE5P0/PAAAAAAAAA66Pw/PAAAAAAAAA88Po/PAAAAAAAAAy+PX/PAAAAAA
            U-
            LAPtAAAAAAS+GAYAAIhLMDRAA4dQlFR19PAUBAUBK+Pk9PGAAAAAAAAI9P88PEAAAAAAAAj9PI8PEAAA8PAAA25Pa2PEAAAAAAAAh8PF6PFAAAAAAAAu8PE5PDAAAAAAAAh8Pq4PBAAAAAAAAc5PzsPBAAAAAAAAI9PL1PBAAAAAAAAh8Px0PBAAAAAAAAI9P9zPAAAAAAAAAj9P8yPAAAAAAAAAS7PnjPAAAAAAAAAK+PswPAAAAAAAAAk+PfwP9/PAAAAAAk+PqvP8/PAAAAAA/+PdvP9/PAAAAAA/+PqvP6/PAAAAAAM/PKhPv/PAAAAAAAAATxPx/PAAAAAAAAAJzPo/PAAAAAAAAAK0PZ/PAAAAAAAAAB3Pd/PAAAAAA
            U-
            LAPtAAAAAAS+HARAAIWeEDRAAoXsRFR79PAUBAcBu8P88PGAAAAAAAAK+Pi8PDAAAAAAAA99P66PDAAAAAAAAK+Pe5PDAAAAAAAA99PE5PCAAAAAAAAu8PbtPDAAAAAAAAk+PX0PCAAAAAAAAj9PqlPAAAAAAAAAm/P7fPAAAAAAAAAAAA1tPCAAAAAAAAAAAzZP9/PAAAA8PAAAmsPBAAAAAAAAAAAzZP+/PAAAAAAoIAGCP8/PAAAAAA4CA9zPV/PAAAA8PVFA1tPt+PAAAAAA
            U-
            LAPtAAAAAAS+IAdAA4ysBDRAAYVWgERC+PAUBAUBU8PAAAHAAAAAAAA/+PM/PEAAAAAAAAk+P88PCAAAAAAAA/+P02PCAAAAAAAAAAAe5PDAAAAAAAAAAAfwPCAAAAAAAAAAAA2PDAAAAAAAAAAAL1PBAAAAAAAADCA9zPAAAAAAAAA4CAJzPAAAAAAAAA4CAHyPAAAAAAAAASDATxPAAAAAAAAA5DASwPAAAAAAAAA5DAFwPAAAAAAAAAsDADvPAAAAAAAAAUEAqvPAAAAAAAAA5DA3vP//PAAAA8P5DAfwP+/PAAAAAAUEAtxP9/PAAAAAASDAvyP8/PAAAAAAUEAK0P9/PAAAAAAfDAL1P6/PAAAAAASDAB3P5/PAAAAAA5DAQ4P2/PAAAA8PSDAe5Pv/PAAAAAAfDA66Pj/PAAAAAA4CAi8PO/PAAAAAA4CAW9Pr/PAAAAAA
            U-
            LAPtAAAAAAS+JAYAAoFSMDRAAo1GvDRC+PAUBAABAAA88PIAAAAAAAAAAAi8PDAAA8PAAAAAAu7PCAAAAAAAABBAt6PCAAAAAAAA4CAf6PBAAAAAAAA4CAQ4PBAAAAAAAA4CAo3PBAAAAAAAA5DAb3PCAAAAAAAAUEAB3PBAAAAAAAAuEAA2PAAAAAAAAA7EAA2PAAAAAAAAAuEAL1PAAAAAAAAArKALrPAAAAAAAAAVFAn2P+/PAAAAAAwFA02P//PAAAAAAIFAb3P8/PAAAAAA7EAq4P9/PAAAAAAVFAE5P6/PAAAAAAuEA45P6/PAAAAAAuEA66P1/PA8PAAAUEAu7Pu/PAAAAAA5DAI8PZ/PAAAAAAfDA88PR/PAAAAAA
            U-
            LAPtAAAAAAS+KAWAAYqKTDRAAIDETDRB+PAMBAIBAAAi8PEAAAAAAAAAAAI8PDAAAAAAAAAAAU7PDAAAAAAAAaAAt6PCAAAAAAAAdCAf6PEAAAAAAAASDA45PCAAAAAAAA5DA45PBAAAAAAAAUEAE5PCAAAAAAAAwFAr5PCAAAAAAAAXGAe5PAAAAAAAAAkGAE5PCAAAAAAAAzHA45PAAAAAAAAACJAF6PAAAA8PAAAPJAt6PAAAAAAAAAEKA66PAAAAAAA8PeKAu7P//PAAAAAAGLAI8P6/PAAAAAAGLAi8P4/PAAAAAAGLAW9Pu/PAAAAAAGLAL+Ps+PAAAAAAeKAM/Pd/PAAAAAA
            U-
            LAPtAAAAAAS+LAsBAA4F+DERAAIKBVGRv9PAEBAkBk+PqCARAAAAAAAAm/P0AAFAAA8PAAAAAA0AACAAAAAAAAm/POBACAAAAAAAAZ/PBBAEAAAAAAAAm/P0AACAAAAAAAAAAAOBAAAAAAAAAAAAAaAADAAAAAAAAAAAaAA//PAAAAAAAAAnAABAAAAAAAAAAA0AACAAAAAAAAAAA0AABAAAAAAAAAAAOBABAAAAAAAABBA1BACAAAAAAAA2BAOBAAAAAAAAAA4CA1BACAAAAAAAASDACCAAAAAAAA8P5DA1BABAAAAAAAAVFACCABAAAAAAEAVFAPCAAAAAAAAEAkGAPCAAAAAAAAAAMHAoBABAAAAAAAAOIA1BABAAAAAAEA5SA4DAAAAAAAAAAeKAoBAAAAAAAAAAgLAPCABAAAAAAAA8MACCABAAAAAAAA+NAPCAAAAAAAAAA+NAqCAAAAAAAAAAaPAcCAAAAAAAA8P2fA5EAAAAAAAAAA2QAcCA+/PAAAAAA0PAqCA//PAAAAAAaPAPCA//PAAAAAAYOAcCA//PAAAAAAYOAqCA+/PAAAAAA8MAqCA9/PAAAAAAiMAEDA8/PAAAAAAGLA3CA7/PAAAAAArKAEDA3/PAAAAAAoIAEDAz/PAAAAAAOIAPCAl/PA8PAAAMHACCA9+PAAAAAA
            U-
            LAPtAAAAAAS+MAgBAAY/bkERAAIWffGR89PAIBAYBdCAAAAFAAAAAAAA4CAAAADAAAAAAAA5DAAAAEAAAAAAAAUEAAAAEAAAAAAAAuEAAAADAAAAAAAAXGAAAAAAAAAAAAAKGABBAEAAAAAAAAzHAAAADAAAAAAAAAIAOBABAAAAAAAAqJA0AABAAAAAAAAqJA0AAAAAAAAAAArKAbBACAAAAAAAAgLAOBAAAAAAAAAAcYAbBAAAAAAAAAA8MA0AAAAAA8PAAA6aA0AAAAAAAAAAA+NAAAAAAAAAAAAAYOAAAAAAAAAAAAA+NAAAAAAAAAAAAAlOAAAAAAAAAAAAAYOAAAABAAAAAA8PYOAM/PAAAAAAAAA+NAl+P//PAAAAAAWNAM/PAAAA8PAAAJNAM/P//PAAAAAA6LAM/P8/PAAAAAAgLAm/P9/PAAAAAArKA/+P7/PAAAAAACJAAAA6/PAAAAAABQAAAAz/PAAAAAAKGAm/Pc+PAAAAAA
            U-
            LAPtAAAAAAS+NAbAA4b/YFRAA4QmkGR39PA0AAUBAAAW9PNAAAAAAAAnAAy+PDAAAAAAAAQCAL+PDAAAAAAAADCA+9PDAAAAAAAA4CA88PDAAAAAAAAoIAS6PCAAAAAAAAuEAJ9PEAAAAAAAAwFAi8PAAAAAAAAAXGA88PCAAAAAAAAKGAI8PCAAAAAAAAOIA88PAAAAEAAEAmHA88PAAAAAAAAAdRA45PAAAAAAAEAoIAJ9PCAAAAAAEAqJAW9PAAAAAAAEAoIAI8PAAAAAAAEAqJAi8PAAAAEAAAAoIAi8PAAAAAAAAAOIAi8P//PAAAAAAoIAI8P+/PAAAAAAmHAi8P+/PAAAAAAzHAi8P5/PAAAAAAMHAi8P4/PAAAAAAyGA88P1/PAAAAAAKGAk9PQ/PAEAAAAKGAL+PF/PAAAAAA
            U-
            LAPtAAAAAAS+OAXAAY46qFRAA4iXXGRL+PAIBAgB4CA+9PFAAAAAAAAOIAU7PCAAAAAAAAuEA88PEAAAAAAAAVFAi8PCAAAAAAAAXGAI8PCAAAAAAAAKGAu7PBAAAAAAAAxGAH7PCAAAAAAAAOIA66PCAAAAAAAAAIAS6PCAAAAAAAAPJAe5PAAAAAAAAA8bAYrPAAAAAAAAAcJAQ4PBAAAAAAAAqJAQ4P//PAAAAAASSAswPBAAAAAAAAoIAq4P+/PAAAAAA4RAtxP+/PAAAA8PoIAR5P6/PA8PAAAmHA45P5/PAAAAAAZHA45P5/PAAAAAAMHA66Pw/PAAAAAAKGAH7Pu+PAAAAAAwFAu7Pa/PAAAAAA
            U-
            LAPtAAAAAAS+PAhBAAIW1WFRAAICqiGRM+PA8AAYB4CAAAAIAAA8PAAAdCAAAACAAAAAAAASDAl+PDAAAAAAAA5DAY+PBAAAAAAAAuEAX9PDAAAAAA8P9FAk9PCAAAEAAAAKGA88PAAAAAAAAAMHA88PCAAAAAAAAOIA88P//PAAAAAAoIAI8PCAAAAAAEACJAI8PBAAAAAAEArKAI8PBAAAAAAAAEKAi8PBAAAAAAEAGLAu7PBAAAAAAEAgLAH7PBAAAAAAAAgLAf6PAAAAAAAEAHMA45PAAAAEAAAA6LAF6PAAAAAAAAAqYAswPAAAAAAAAA6LAb3P//PAAAAAACYAmsPBAAAAAAAA2fAkhP//PAAAAAACJAN2PAAAAAAAAAoIAA2P//PAAAAAAZHAb3P+/PAAAAAAkGAo3P//PAAAAAAVFAQ4P+/PAAAAAAUEAq4P9/PAAAAAAMHAjzP7/PAAAAAAdCAs6Pw/PAAAAAAdCAU7Po/PAEAAAAcBAI8Pw+PAAAAAA
            U-
            LAPtAAAAAAS+QAfAAIwm1FRAAoqCPGRI+PAUBAUB4CAbBAIAAAAAAAADCAAAACAAAAAAAAdCAAAAEAAAAAAAAQCAAAACAAAAAAAAfDAAAADAAAAAAAASDAAAACAAAAAAAA5DAAAACAAAAAAAAUEAAAACAAAAAAAAuEAl+PAAAAAAAAAgLAf6PCAAAAAAAAXGAI8PAAAAAAAAAMHAs6PBAAAAAAAAmHAf6PBAAAAAAAAzHAe5PAAAAAAAAAoIAQ4PAAAAAAAAAoIAO3PAAAAAAAAAPJAN2PAAAAAAAAACJAm1PAAAAAAAAAPJAx0P//PAAAAAAEKAWzP+/PAAAAAAqJAjzP+/PAAAA8PCJA8yP+/PAAAAAACJAJzP//PAAAAAA1IAhyP+/PAAAAAAWcA/PP9/PAAAAAAIFAL1Px/PAAAA8PhEAA2P3/PAAAAAASDAn2Px/PAAAAAA4CAC4Pg/PAAAAAA2BAq4PE/PAAAAAA
            U-
            LAPtAAAAAAS+RAaAAIxVcGRAAITx4FRB+PAcBAIBDCAS6PEAAAAAAAA2BAr5PEAAAAAAAAdCAo3PBAAAAAAAA4CAn2PEAAAAAAAA4CAA2PEAAAAAAAASDAL1PCAAAAAAAASDA9zPCAAAAAAAAfDAwzPAAAAAAAAA5DAJzPCAAAAAAAAsDAHyP//PAAAAAA5DAtxPAAAAAAAAA5DAHyPAAAAAAAAAmHA0jPAAAAAAAAA5DAvyPAAAAAAAAAMHA4mPAAAAAAA8PSDAX0P+/PAAAAAAFDAx0P9/PAAAAAA4CAL1P+/PAAAAAAQCAm1P7/PA8PAAAdCA02P6/PAAAAAAdCA13P3/PAAAAAAcBAq4P0/PAAAA8PcBAe5Pq/PAAAAAA0AAf6PK/PAAAAAABBAu7Ph/PAAAAAA
            U-
            LAPtAAAAAAS+SAbAAYYTkGRAAI0glFRB+PAcBA8AAAA88PFAAAAAAAAaAAu7PDAAAAAAAAcBAS6PFAAAAAAAA2BAq4PEAAAAAAAADCA13PCAAAAAAAAQCAa2PCAAAAAAAAFDAx0PDAAAAAAAAwFAemPBAAAAAAAA4CAtxPDAAAAAAAAKGAliPBAAAAAAAA4CA5wPAAAAAAAAA4CAfwPBAAAAAAAAdCASwP//PAAAAAAdCATxPBAAAAAAAAQCAtxPBAAAAAAAA5DABkPAAAAAAAAA2BA8yP9/PAAAAAAcBAjzPBAAAAAAAAcBAX0P//PA8PAAAcBAm1P+/PAAAAAAnAAA2P8/PAAAAAA0AAa2P8/PAAAAAAAAAQ4P3/PAAAAAAAAAE5Pz/PAAAAAAAAAf6Pp/PAAAAAAAAA02P/+PAAAAAA
            U-
            LAPtAAAAAAS+TAbAAYLzpGRAAYzMGFRF+PAcBAABAAAk9PEAAAAAAAAAAAI8PEAAAAAAAAAAAH7PCAAAAAAAAAAAe5PDAAAAAAAAAAAq4PDAAAAAAAAnAAb3PCAAAAAAAAaAAm1PBAAAAAAAAAAAX0PCAAAAAAAAAAAjzPAAAAAAAAAAAAtxPBAAAAAAAAAAAtxPBAAAAAAAAAAA3vPAAAAAAAAAAAAQvPAAAAAAAAAAAAPuPAAAAAAAAAK+P1tPAAAAAAAAA99PPuPAAAAAAAAA81Pv6OAAAAAAAAAj9PTxPAAAA8PA8PS7PqlP//PAAAAAAK+PK0P7/PAAAAAAk+PN2P5/PAAAA8Pk+PO3P3/PAAAAAA/+PE5Px/PAAAAAAm/P66Pm/PAAAAAAAAAi8PT/PAAAA8PAAAY+PZ/PAAAAAA
            U-
            LAPtAAAAAAS+UAaAAoGZrGRAAYEpdERP+PAYBAABAAAU7PLAAAAAAAAAAAH7PBAAAAAAAA/+Pf6PCAAAAAAAAk+PE5PCAAAAAAAAK+PO3PCAAAAAAAAj9PN2PAAAAAAAAAj9PL1PBAAAAAAAAI9PwzPBAAAAAAAAu8PJzPBAAAAAAAAH8P8yPBAAAAAAAAH8PtxPAAAAAAAAAs7PtxPAAAAAAAAAS7PUyPAAAAAAAAAW2P0jPAAAAAAAAAr6PhyP//PAAAA8PS7PJzP+/PAAAAAAS7PWzP+/PAAAAAAF7PX0P9/PAAAAAAS7PA2P8/PAAAAAAp5PpuP7/PAAAAAAI9Pf6P1/PAAAA8PI9P13P3/PAAAAAAAAAl+Pk/PAAAAAAAAAAAAV/PAAAAAAAAAAAAT/PAAAAAA
            U-
            LAPtAAAAAAS+VAbAA4lVpGRAAYZ5DERJ+PAYBA0Ak+P77PJAAAAAAAAr6Pb3PDAAAAAAAAI9Pf6PDAAAAAAAAH8PE5PBAAAAAAAAU8Pq4PCAAAAAAAAF7Po3PCAAAAAAAAQ6Pn2PCAAAAAAAAG0P/rPBAAAAAAAAP5PL1PCAAAAAAAAN4PL1PAAAAAAAAA04Px0PAAAAAAAAAA4Px0PAAAAAAAAAy3Px0PAAAAAAAAAy3Pm1PAAAAAAAAA04Pm1PAAAAAAAAA04Pn2PAAAAAAAAAssPhoPAAAA8PAAAs7Pf6P6/PAAAAAAH8Pu7P9/PAAAAAAw9P88P6/PAAAAAA99Px9P4/PAAAAAAm/Pm/P5/PAAAAAAAAAAAA0/PAAAAAAAAAAAAp/PAAAAAAAAAAAAD/PAAAAAAaAAPCAd/PAAAAAA
            U-
            LAPtAAAAAAS+WAZAAomYYGRAAYufnDRJ+PAcBAABI9P+9PFAAAAAAAAj9Pi8PCAAAAAAAAu8PI8PDAAAAAAAAH8PH7PCAAAAAAAAu8PU7PCAAAAAAAAF7P66PCAAAAAAAAS7PS6PCAAA8PAAAr6PF6PAAAAAAAAA25Pe5PAAAAAAAAAp5Pe5PDAAAAAAAAqyPhyPBAAAAAAAAN4Pq4PCAAA8PA8PoxPHyPAAAAAAAAAy3PR5PAAAAAAAAA04Pe5PAAAAAAAAAa4Pe5PAAAAAAAAAQrPpuPAAAAAAAAAQ6P66P+/PAAAA8Pr6Pu7P//PAAAAAAs7Pi8P9/PAAAAAAu8P88P6/PAAAAAAj9Px9P1/PAAAAAAK+Py+Pn/PA8PA8P/+PAAAv+PAAAAAA
            U-
            LAPtAAAAAAS+XAiBAAYfdLDRAAoOLkDRH+PAYBAIBAAAW9PIAAAAAAAAAAAY+PDAAAAAAAAAAAx9PEAAAAAAAAAAAx9PCAAAAAAAAAAAJ9PDAAAAAAAA2BAi8PCAAAAAAAA4CA77PCAAAAAAAAfDAU7PCAAAAAAAAUEAU7PCAAAAAAAAUEAS6PCAAAAAAAAVFAf6PAAAAAAAAAwFA45PBAAAAAAAAxGAe5PBAAAAAAAAkGAF6PAAAAAAAAAzHAe5PAAAAAAAAAmHAe5PAAAAAAAAAoIAE5PAAAAAAAAAPJAe5PBAAAAAAAACJAr5P//PA8PAAAqJAE5P//PAAAAAAqJAq4PAAAAAAAAACJAQ4P//PAAAAAAPJAC4P+/PAAAAAACJAb3P9/PAAAAAAOIAb3P+/PAAAA8PzHA02P9/PAAAAAAMHAB3P9/PAAAAAA8MApuP5/PAAAAAAwFA13Px/PAAAA8PuEAE5Pz/PAAAAAAhEAS6Pl/PAAAAAAsDAU7PG/PAAAAAA5DAW9Pk/PAAAAAA
            U-
            LAPtAAAAAAS+YAgBAAodzfDRAAoSZGDR09PAMBAABZ/Px9PJAAAAAAAAAAAM/PEAAAAAA8PAAAy+PEAAAAAAAAAAAM/PCAAAAAAAAAAAl+PFAAA8PAAAAAAy+PDAAAAAAAAnAAL+PCAAAAAAAAcBAy+PBAAAAAAAAcBAy+PCAAAAAAAA2BAl+PDAAAAAAAA2BAY+PDAAAAAAAARKAq4PBAAAAAAAASDAW9PEAAAAAAAA5DA+9PBAAAAAAAAUEAX9PBAAAAAAAAUEA88PAAAAAAAAAuEA88PAAAAAAAAAwFAi8PAAAAAAAAAwFAI8PAAAAAAAAAXGAu7PAAAAAAAAAyGAI8PAAAAAAAAAkGAu7PAAAAAAAAAzHAH7PAAAAAAA8PmHAU7PAAAAAAAAAaPA13P//PAAAAAAzHAi8P7/PAAAAAAmHAx9P9/PAEAAAAzHAk9P7/PAAAAAAYOAX9P4/PAAAAAAKGAm/Pc/PAAAA8PHMAAAA7+PAAAAAA
            U-
            LAPtAAAAAAS+ZAZAAY+xvDRAA4G77CRI+PAUBA0ABBAi8PKAAAAAAAAQCAW9PDAAAAAAAA4CA88PBAAAAAAAA5DAX9PDAAAAAAAAUEAi8PCAAAAAAAAVFAi8PCAAAAAAAAKGAi8PCAAAAAAAAZHAi8PCAAAAAAAAMHAJ9PCAAAAAAAAAIA88PAAAAAAAAA1IAW9PBAAAAAAAAHTAI8PBAAAAAAAAEKAx9PAAAAAAAAArKAY+PAAAAAAAAAEKAY+P//PAAAAAArKAl+P9/PAAAAAAeKAy+P8/PA8PAAArKAl+P8/PAAAAAAEKAY+P7/PAAAAAAcJAL+P4/PAAAAAAqJAy+P0/PAAAAAAoIAm/Pv/PAAAAAAOIAM/PX/PAAAAAAMHAM/PK/PA8PAAA
            U-
            LAPtAAAAAAS+aAXAAYboPERAAYnowCRK+PAIBAsA5DAi8PKAAAAAAAASDAy+PDAAAAAAAA5DAl+PBAAAAAAAA7EAy+PBAAAAAAAAIFAy+PBAAAAAAAAwFAl+PBAAAAAAAAxGAm/P//PAAAAAAYOAm/PCAAAAAAAAOIAAAABAAAAAAAAoIAm/PDAAAAAAAAPJAAAABAAAAAAAAqJAAAAAAAAAAAAAIUAAAAAAAAAAAIAeKAAAA+/PAAAAEArKA1BA9/PAAAAEAGLAoBA9/PAAAAEAEKAoBA8/PAAAAEAEKAPCA7/PAAAAEAPJAqCA4/PAAAAAACJACCAz/PAAAAAAzHAqCAn/PAAAAAAWNASEA/+PAAAAAA
            U-
            LAPtAAAAAAS+bAZAA4UfzERAAYxYuCRG+PAQBA0AUEAAAAMAAAAAAMASDAAAADAAAAAAAAfDA0AACAAAAAAEAsDAAAACAAAAAAAAhEAaAAEAAAAAAAAuEA0AABAAAAAAAAVFAAAACAAAAAAAAwFA0AACAAAAAAAAKGAbBACAAAAAAAAxGA0AACAAAAAAAAmHAOBAAAAAAAA8POIA1BABAAAAAAAAoIAPCAAAAAAAAAAPJAcCAAAAAAAAAAqJAeDAAAAA8PAAAjUA8GAAAAAAAAAArKASEA//PAAAAAAGLA5EA8/PAAAAAAeKA4DA//PAAAAAAWUALIA8/PAAAAAAoIAeDAv/PAAAAAAAIAEDAw/PA8PAAAOIAEDAd/PAAAAAAxGAcCA++PAAAAAA
            U-
            LAPtAAAAAAS+cAXAA4YTbFRAA4399CRE+PAABA0AQCAAAALAAAAAAAADCAAAADAAAAAAAA4CAAAADAAAAAAAA4CAAAACAAAAAAAA5DAAAABAAAAAAAASDAOBABAAAEAAAA5DAOBADAAAAAAAAsDA1BABAAAAAAAAhEAPCAAAAAAAAAAuEAcCAAAAAAAAAAUEAqCAAAAAAAAAAuEAEDAAAAAAAAAAVFAEDA//PAAAAAA7EA3CABAAAAAAAAuEAEDAAAAAEAAAAuEAEDA9/PAAAAAARKAIGA+/PAAAAAAUEAEDA4/PAAAAAAuEA3CA4/PAAAAAAUEApCAy/PAAAAAAzHAUFAm/PAAAAAASDAcCAl+PAAAAAA
            U-
            LAPtAAAAAAS+dA8DAAo2ltFRAAIaYDDR+9PAUBA0AwFAcCASAAA8PAAAQCA1BAEAAAAAAAA4CACCACAAAAAAAA4CApCAAAAAAAAAAFDAPCAAAAAAAAAASDAEDABAAAAAAAASDA3CAAAAAAAAAA4CAeDAAAAAAAAAAfDAEDAAAAAAAAAASDAeDAAAAAAAAAASDAEDAAAAAAAAAAFDAeDA+/PAAAAAAQCAEDAAAAAAAAAA4CAqCA+/PAAAAAA7EAGFAAAAAAAAAAcBAPCA+/PAAAAAA2BACCAAAAAAAAAABBAOBAAAAAAAAAAcBAbBAAAAA8PAAA0AAOBAAAAAAAAAAnAAaAA+/PAAAAAAAAAaAABAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/+Py+PAAAAAAAAAk+Py+PBAAAAAAAAk+PL+PAAAA8PAAAK+PY+P//PAAAAAAk+Px9PBAAAAAAAA99P+9PAAAAAAAAAw9Px9PAAAAAAAAAj9PW9PCAAAAAAAAj9Pk9PAAAAAAAAAI9P88P//PAAAAEAI9P88PAAAAAAAAA04Pe5P+/PAAAAAAO5PE5PDAAAAAAAAs7Pi8PCAAAAAAAA04Pq4P//PAAAAAAu8Pi8PBAAAAAAAAh8P88PAAAAAAA8Pu8Pv8PBAAAAAAAAu8PX9PAAAAAAAAA78P88PAAAAAAAAAw9Px9PAAAAAAAAAh8Pk9PBAAAAAAAAI9Px9P//PAAAAAA46PI8PAAAAAAAAAI9Px9PBAAAAAAAAh8PY+P//PAEAAAAu8PL+PAAAAAAAAAH8P+9PAAAAAAAAAu8Px9P//PAAAAAAs7PY+PBAAAAAAAAH8Px9PBAAAAAAAAs7PW9PAAAAAAAAAs7PY+PAAAAAAAAAs7PX9PBAAAAAAAAs7Pk9PBAAAAAAAAy3PH7PAAAAAAAAAH8P+9PAAAAAAAAAH8PL+PAAAAAAAAAI9PY+PAAAAAAA8PS7PW9PAAAAAAAAAk+PM/PAAAAAAAAAk+PAAABAAA8PAAA/+PM/PAAAAAAAAA/+PAAAAAAAAAAAAk+PZ/PBAAAAAAAAM/PAAABAAAAAAAA/+PAAA+/PAAAAAA/+Pm/PAAAAAAAAAk+PAAABAAAAAA8Pk+Pm/PBAAAAAAAAk+PAAA+/PAAAAAAk+Pm/PBAAAAAAAAI9Pm/PBAAAAAAAAK+Pm/PAAAAAAAAAK+PAAAAAAAAAAAA99Pm/PAAAA8PAAAI9P/+PAAAAAAAAAj9Pm/PAAAAAAAAAI9PM/PAAAAAAAAAI9PM/PBAAAAAAAAu8PM/PBAAAAAAAAI9P/+PAAAAAAAAAu8PM/PAAAAAAAAA78Pm/PAAAA8PAAAI9PM/PAAAAAAAAAu8Pm/PAAAAAAAAAI9Pm/PAAAAAAAAAI9PZ/PBAAAAAAAAj9Pm/PBAAAAAAAAr6PM/PAAAAAAAAAw9Pm/PAAAAAAAAAj9PAAAAAAAAAAAAj9PAAAAAAAAAAAAw9PAAAAAAAAAAAAI9Pm/PAAAAAAAAAI9PAAAAAAAAAAAAH8Pm/PAAAAAAAAAh8PAAAAAAAAAAAAU8PAAAAAAAAAAAAF7PAAAAAAAAAAAAS7PAAABAAAAAAAAr6PAAA//PAAAAAA25PAAAAAAAEAAAAP5PAAAAAAAAAAAA04PAAAAAAAAAAAAN4Pm/P+/PAAAAAAwuPl+P//PAAAAAA+2PM/P8/PAAAAAAY3PM/P9/PAEAAAAx2Pl+P7/PAAAAAAY3P+9P3/PAAAAAAy3PL+Pt/PAAAAAAy3Py+P2+PAAAAAA04Px9PY/PAAAAAA
            U-
            LAPtAAAAAA*+eIAAAAg+AAAAoABAAAICB+
            LAPtAAAAAAP+fAAAAg/AAAAg/ArAAQmZmZW//P
            LAPtAAAAAAF+gBAAAAAdKbJCEAAAAgVcaJCEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABB
            U-
        ").await
    });
}
