use crate::region::*;
use crate::description::*;

use flo_curves::*;
use flo_curves::bezier::*;

use std::sync::*;
use std::time::{Duration};

///
/// Motion effect that's generated by fitting to a curve
///
pub struct FittedMotionEffect {

}
