[package]
name                    = "motion_effect_demo"
version                 = "0.1.0"
authors                 = ["Andrew Hunter <andrew@logicalshift.co.uk>"]
description             = "Demonstrates the basic motion effect in flo_canvas_animation"
edition                 = "2018"

[dependencies]
flo_draw                = "0.4"
flo_canvas_animation    = "0.3"
futures                 = "0.3"
futures-timer           = "3.0"
flo_stream              = "0.7"
flo_curves              = "0.6"
