[package]
name                    = "motion_effect_demo"
version                 = "0.1.0"
authors                 = ["Andrew Hunter <andrew@logicalshift.co.uk>"]
description             = "Demonstrates path arithmetic in flo_curves"
edition                 = "2018"

[dependencies]
flo_draw                = "0.3"
flo_canvas_animation    = "0.3"
futures                 = "0.3"
futures-timer           = "3.0"
flo_stream              = "0.6"
flo_curves              = "0.5"
